baseURL = '/'
languageCode = 'en-us'
title = 'The Geargineer - Creative Outdoor Gear'
theme = 'lugo'
[markup.goldmark.renderHooks.image]
useEmbedded = 'fallback'

[markup.goldmark.renderHooks.link]
useEmbedded = 'fallback'
